const sequences = {
  "1": [
    "data/BowTie01_tutorial.scap",
    "data/Professional1_mixer_view2_presentation_t_m_result_cluster.scap",
    "data/Professional3_potato_chip_view1_presentation_t_m_result_cluster.scap",
    "data/Professional1_hairdryer_view1_concept_t_m_result_cluster.scap",
    "data/hand1_t_m_result_cluster.scap",
  ],
  "2": [ // done
    "data/BowTie01_tutorial.scap",
    "data/Professional2_house_view2_presentation_t_m_result_cluster.scap",
    "data/Professional3_potato_chip_view1_presentation_t_m_result_cluster.scap",
    "data/03sketch_t_m_result_cluster.scap",
    "data/mug_t_m_result_cluster.scap",
  ],
  "3": [
    "data/BowTie01_tutorial.scap",
    "data/06sketch_t_m_result_cluster.scap",
    "data/11sketch_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_05_t_m_result_cluster.scap",
    "data/student3_house_view1_concept_t_m_result_cluster.scap",
  ],
  "4": [
    "data/BowTie01_tutorial.scap",
    "data/student1_wobble_surface_view1_presentation_t_m_result_cluster.scap",
    "data/student3_house_view1_presentation_t_m_result_cluster.scap",
    "data/Professional2_house_view2_concept_t_m_result_cluster.scap",
    "data/05sketch_t_m_result_cluster.scap",
  ],
  "5": [
    "data/BowTie01_tutorial.scap",
    "data/plushie1_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_02_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_06_t_m_result_cluster.scap",
  ],
  "6": [
    "data/BowTie01_tutorial.scap",
    "data/hamstertoon_t_m_result_cluster.scap",
    "data/clock_c_1_u_1_h_t_result_proximity.scap",
  ],
  "7": [
    "data/BowTie01_tutorial.scap",
    "data/02sketch_t_m_result_cluster.scap",
    "data/09sketch_t_m_result_cluster.scap",
    "data/student1_wobble_surface_view1_concept_t_m_result_cluster.scap",
  ],
  "8": [
    "data/BowTie01_tutorial.scap",
    "data/04sketch_t_m_result_cluster.scap",
    "data/lionhat_t_m_result_cluster.scap",
  ],
  "9": [
    "data/BowTie01_tutorial.scap",
    "data/student1_wobble_surface_view1_presentation_t_m_result_cluster.scap",
    "data/student3_house_view1_presentation_t_m_result_cluster.scap",
    "data/04sketch_t_m_result_cluster.scap",
    "data/05sketch_t_m_result_cluster.scap",
  ],
  "10": [
    "data/BowTie01_tutorial.scap",
    "data/Professional1_mixer_view2_presentation_t_m_result_cluster.scap",
    "data/Professional3_potato_chip_view1_presentation_t_m_result_cluster.scap",
    "data/student1_wobble_surface_view1_presentation_t_m_result_cluster.scap",
    "data/student3_house_view1_presentation_t_m_result_cluster.scap",
  ],
  "11": [
    "data/BowTie01_tutorial.scap",
    "fashion/Artist_01_Sketch_01_t_m_result_cluster.scap",
    "fashion/Artist_01_Sketch_02_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_01_t_m_result_cluster.scap",
  ],
  "12": [
    "data/BowTie01_tutorial.scap",
    "fashion/Artist_02_Sketch_03_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_04_t_m_result_cluster.scap",
    "fashion/Artist_01_Sketch_03_t_m_result_cluster.scap",
    "fashion/Artist_01_Sketch_04_t_m_result_cluster.scap",
  ],
  "13": [
    "data/BowTie01_tutorial.scap",
    "fashion/Artist_02_Sketch_05_t_m_result_cluster.scap",
    "data/student3_house_view1_concept_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_06_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_07_t_m_result_cluster.scap",
  ],
  "14": [
    "data/BowTie01_tutorial.scap",
    "data/08sketch_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_08_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_09_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_01_t_m_result_cluster.scap",
  ],
  "15": [
    "data/BowTie01_tutorial.scap",
    "fashion/Artist_03_Sketch_03_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_04_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_05_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_02_t_m_result_cluster.scap",
  ],
  "15b": [
    "data/BowTie01_tutorial.scap",
    "fashion/Artist_03_Sketch_03_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_04_t_m_result_cluster.scap",
    "data/lionhat_t_m_result_cluster.scap",
  ],
  "oldset1": [
    "old_set/12345_c_1_u_1_h_t_result_proximity.scap",
    "old_set/BB04_c_1_u_0_h_t_result_proximity.scap",
    "old_set/Bee02_c_1_u_1_h_t_result_proximity.scap",
    "old_set/BowTie01_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Bug02Fxd_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Bunny02Fxd_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Bunny05_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Bunny08fxd01c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Flower03_c_1_u_1_h_t_result_proximity.scap",
    "old_set/GOEagle03_c_1_u_0_h_t_result_proximity.scap",
    "old_set/GOSmart06_c_1_u_0_h_t_result_proximity.scap",
    "old_set/Giraffe02_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Koala04_c_1_u_1_h_t_result_proximity.scap",
    "old_set/LbkEagle02_c_1_u_0_h_t_result_proximity.scap",
    "old_set/LbkSmart03_c_1_u_0_h_t_result_proximity.scap",
    "old_set/Penguinfxd01_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Pig01c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Pig02fxd01_c_1_u_1_h_t_result_proximity.scap",
    "old_set/SharkArtistC02fxd01_c_1_u_1_h_t_result_proximity.scap",
    "old_set/TriceratopsArtistC02fxd02_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Tucanfxd01_c_1_u_1_h_t_result_proximity.scap",
  ],
  "oldset2": [
    "old_set/archi10c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/building_c_1_u_1_h_t_result_proximity.scap",
    "old_set/carc_c_1_u_1_h_t_result_proximity.scap",
    "old_set/duck_c_1_u_1_h_t_result_proximity.scap",
    "old_set/fairydenc_c_1_u_1_h_t_result_proximity.scap",
    "old_set/fish_c_1_u_1_h_t_result_proximity.scap",
    "old_set/fruit_c_1_u_0_h_t_result_proximity.scap",
    "old_set/geometry_c_1_u_1_h_t_result_proximity.scap",
    "old_set/giraffe_c_1_u_1_h_t_result_proximity.scap",
    "old_set/girl_c_1_u_1_h_t_result_proximity.scap",
    "old_set/grandpa_c_1_u_1_h_t_result_proximity.scap",
    "old_set/house_c_1_u_1_h_t_result_proximity.scap",
    "old_set/lady_c_1_u_1_h_t_result_proximity.scap",
    "old_set/lion_c_1_u_1_h_t_result_proximity.scap",
    "old_set/mecha4c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/mno_c_1_u_1_h_t_result_proximity.scap",
    "old_set/mouse7c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/pqr_c_1_u_1_h_t_result_proximity.scap",
    "old_set/ring_c_1_u_1_h_t_result_proximity.scap",
    "old_set/shesh_c_1_u_0_h_t_result_proximity.scap",
    "old_set/stu_c_1_u_1_h_t_result_proximity.scap",
    "old_set/veyron11c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/vwx_c_1_u_1_h_t_result_proximity.scap",
    "old_set/waiter_c_1_u_1_h_t_result_proximity.scap",
    "old_set/yz_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o1": [
    "data/BowTie01_tutorial.scap",
    "old_set/yz_c_1_u_1_h_t_result_proximity.scap",
    "old_set/BB04_c_1_u_0_h_t_result_proximity.scap",
    "old_set/Bee02_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Pig02fxd01_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o2": [
    "data/BowTie01_tutorial.scap",
    "old_set/Bug02Fxd_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Bunny02Fxd_c_1_u_1_h_t_result_proximity.scap",
    "old_set/fish_c_1_u_1_h_t_result_proximity.scap",
    "old_set/grandpa_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o3": [
    "data/BowTie01_tutorial.scap",
    "old_set/Flower03_c_1_u_1_h_t_result_proximity.scap",
    "old_set/GOEagle03_c_1_u_0_h_t_result_proximity.scap",
    "old_set/GOSmart06_c_1_u_0_h_t_result_proximity.scap",
    "old_set/Giraffe02_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o4": [
    "data/BowTie01_tutorial.scap",
    "old_set/Koala04_c_1_u_1_h_t_result_proximity.scap",
    "old_set/LbkEagle02_c_1_u_0_h_t_result_proximity.scap",
    "old_set/LbkSmart03_c_1_u_0_h_t_result_proximity.scap",
    "old_set/Penguinfxd01_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o5": [
    "data/BowTie01_tutorial.scap",
    "old_set/Pig01c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/12345_c_1_u_1_h_t_result_proximity.scap",
    "old_set/SharkArtistC02fxd01_c_1_u_1_h_t_result_proximity.scap",
    "old_set/TriceratopsArtistC02fxd02_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o6": [
    "data/BowTie01_tutorial.scap",
    "old_set/Tucanfxd01_c_1_u_1_h_t_result_proximity.scap",
    "old_set/archi10c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/building_c_1_u_1_h_t_result_proximity.scap",
    "old_set/carc_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o7": [
    "data/BowTie01_tutorial.scap",
    "old_set/duck_c_1_u_1_h_t_result_proximity.scap",
    "old_set/fairydenc_c_1_u_1_h_t_result_proximity.scap",
    "old_set/fruit_c_1_u_0_h_t_result_proximity.scap",
    "old_set/Bunny05_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o8": [
    "data/BowTie01_tutorial.scap",
    "old_set/geometry_c_1_u_1_h_t_result_proximity.scap",
    "old_set/giraffe_c_1_u_1_h_t_result_proximity.scap",
    "old_set/girl_c_1_u_1_h_t_result_proximity.scap",
    "old_set/Bunny08fxd01c_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o9": [
    "data/BowTie01_tutorial.scap",
    "old_set/house_c_1_u_1_h_t_result_proximity.scap",
    "old_set/lady_c_1_u_1_h_t_result_proximity.scap",
    "old_set/lion_c_1_u_1_h_t_result_proximity.scap",
    "old_set/mecha4c_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o10": [
    "data/BowTie01_tutorial.scap",
    "old_set/mno_c_1_u_1_h_t_result_proximity.scap",
    "old_set/mouse7c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/pqr_c_1_u_1_h_t_result_proximity.scap",
    "old_set/ring_c_1_u_1_h_t_result_proximity.scap",
  ],
  "o11": [
    "data/BowTie01_tutorial.scap",
    "old_set/shesh_c_1_u_0_h_t_result_proximity.scap",
    "old_set/stu_c_1_u_1_h_t_result_proximity.scap",
    "old_set/veyron11c_c_1_u_1_h_t_result_proximity.scap",
    "old_set/vwx_c_1_u_1_h_t_result_proximity.scap",
    "old_set/waiter_c_1_u_1_h_t_result_proximity.scap",
  ],
  "r1": [
    "data/BowTie01_tutorial.scap",
    "remaining/abc_SA_cluster.scap",
    "remaining/jkl_SA_cluster.scap",
    "remaining/Bee01_SA_cluster.scap",
    "remaining/Bunny01_SA_cluster.scap",
    "remaining/spiral_SA_cluster.scap",
  ],
  "r2": [
    "data/BowTie01_tutorial.scap",
    "remaining/def_SA_cluster.scap",
    "remaining/Bunny03_SA_cluster.scap",
    "remaining/Bee03_SA_cluster.scap",
    "remaining/parallel_SA_cluster.scap",
  ],
  "r3": [
    "data/BowTie01_tutorial.scap",
    "remaining/ghi_SA_cluster.scap",
    "remaining/Bee04_SA_cluster.scap",
    "remaining/Bunny04_SA_cluster.scap",
    "remaining/circles_SA_cluster.scap",
    "remaining/Giraffe03_SA_cluster.scap",
  ],
  "forsilver": [
    "fashion/Artist_02_Sketch_01_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_02_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_03_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_04_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_08_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_09_t_m_result_cluster.scap",
  ],
  "remaining_fashion": [
    "data/BowTie01_tutorial.scap",
    "fashion/Artist_01_Sketch_03_t_m_result_cluster.scap",
    "fashion/Artist_01_Sketch_04_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_01_t_m_result_cluster.scap",
    "fashion/Artist_03_Sketch_06_t_m_result_cluster.scap",
  ],
  "remaining_artist": [
    "data/BowTie01_tutorial.scap",
    "data/plushie1_t_m_result_cluster.scap",
    "data/06sketch_t_m_result_cluster.scap",
    "data/11sketch_t_m_result_cluster.scap",
    "data/08sketch_t_m_result_cluster.scap",
    "old_set/fruit_c_1_u_0_h_t_result_proximity.scap",
  ],
  "aug_data": [
    "data/BowTie01_tutorial.scap",
    "aug_data/branch1.scap",
    "aug_data/branch2.scap",
    "aug_data/branch3.scap",
    "aug_data/branch4.scap",
    "aug_data/branch5.scap",
    "aug_data/branch6.scap",
    "aug_data/branch7.scap",
    "aug_data/branch8.scap",
    "aug_data/branch9.scap",
  ],
  "16": [
    "data/BowTie01_tutorial.scap",
    "ind/Professional1_bumps_view2_presentation_orig_cluster.scap",
    "fashion/Artist_02_Sketch_05_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_06_t_m_result_cluster.scap",
    "fashion/Artist_02_Sketch_07_t_m_result_cluster.scap",
  ],
  "17": [
    "data/BowTie01_tutorial.scap",
    "ind/Professional3_mouse_view1_presentation_orig_cluster.scap",
    "ind/student7_shampoo_bottle_view1_presentation_orig_cluster.scap",
    "ind/student3_waffle_iron_view1_presentation_orig_cluster.scap",
    "ind/student4_potato_chip_view1_concept_orig_cluster.scap",
  ],
  short: [
    "data/BowTie01_tutorial.scap",
  ],
  "new_init_1": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/lion.scap",
    "new_init_clusters/Artist_01_Sketch_03_apost.scap",
    "new_init_clusters/Artist_01_Sketch_04_apost.scap",
    "new_init_clusters/Artist_01_Sketch_01_apost.scap",
    "new_init_clusters/Artist_01_Sketch_02_apost.scap",
  ],
  "new_init_2": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/Artist_02_Sketch_03_apost.scap",
    "new_init_clusters/Artist_02_Sketch_04_apost.scap",
    "new_init_clusters/Professional1_hairdryer_view1_concept_apost.scap",
    "new_init_clusters/Artist_03_Sketch_06_apost.scap",
  ],
  "new_init_3": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/Artist_02_Sketch_06_apost.scap",
    "new_init_clusters/Artist_02_Sketch_07_apost.scap",
    "new_init_clusters/Artist_03_Sketch_01_apost.scap",
  ],
  "new_init_4": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/Professional2_house_view2_presentation_apost.scap",
    "new_init_clusters/Professional3_potato_chip_view1_presentation_apost.scap",
    "new_init_clusters/student3_house_view1_presentation_apost.scap",
    "new_init_clusters/Artist_02_Sketch_05_apost.scap",
  ],
  "new_init_5": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/Professional1_mixer_view2_presentation_apost.scap",
    "new_init_clusters/Professional2_house_view2_concept_apost.scap",
    "new_init_clusters/Professional3_potato_chip_view1_concept_apost.scap",
    "new_init_clusters/student1_wobble_surface_view1_presentation_apost.scap",
  ],
  "new_init_6": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/02sketch_apost.scap",
    "new_init_clusters/fruit_apost.scap",
    "new_init_clusters/11sketch_apost.scap",
    "new_init_clusters/mug_apost.scap",
  ],
  "new_init_7": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/hand1_apost.scap",
    "new_init_clusters/hamstertoon_apost.scap",
    "new_init_clusters/plushie1_apost.scap",
    "new_init_clusters/clock_apost.scap",
  ],
  "new_init_8": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/03sketch_apost.scap",
    "new_init_clusters/05sketch_apost.scap",
    "new_init_clusters/06sketch_apost.scap",
    "new_init_clusters/shesh_apost.scap",
  ],
  "new_init_9": [
    "data/BowTie01_tutorial.scap",
    "new_init_clusters/lion_apost.scap",
    "new_init_clusters/04sketch_apost.scap",
    "new_init_clusters/08sketch_apost.scap",
    "new_init_clusters/09sketch_apost.scap",
  ],
  "0512": [
    "data/BowTie01_tutorial.scap",
    "0512/Bunny08fxd01c.scap",
    "0512/GOEagle03.scap",
    "0512/Penguinfxd01.scap",
    "0512/ring.scap",
    "0512/TriceratopsArtistC02fxd02.scap",
  ],
  "fromscratch": [
    "data/from_scratch.scap",
  ],
  "test_ungrouped": [
    "data/BowTie01_tutorial_ungrouped.scap",
  ],
  "alt1": [
    "data/BowTie01_tutorial.scap",
    "alt_init_clusters/Professional1_bumps_view2_presentation_apost.scap",
    "alt_init_clusters/Professional3_mouse_view1_presentation_apost.scap",
    "alt_init_clusters/02sketch_apost.scap",
    "alt_init_clusters/fruit_apost.scap",
    "alt_init_clusters/11sketch_apost.scap",
    "alt_init_clusters/mug_apost.scap",
  ],
  "alt2": [
    "data/BowTie01_tutorial.scap",
    "alt_init_clusters/hand1_apost.scap",
    "alt_init_clusters/hamstertoon_apost.scap",
    "alt_init_clusters/plushie1_apost.scap",
    "alt_init_clusters/clock_apost.scap",
  ],
  "alt3": [
    "data/BowTie01_tutorial.scap",
    "alt_init_clusters/Professional2_house_view2_concept_apost.scap",
    "alt_init_clusters/student4_potato_chip_view1_concept_apost.scap",
    "alt_init_clusters/03sketch_apost.scap",
    "alt_init_clusters/05sketch_apost.scap",
    "alt_init_clusters/06sketch_apost.scap",
    "alt_init_clusters/shesh_apost.scap",
  ],
  "alt4": [
    "data/BowTie01_tutorial.scap",
    "alt_init_clusters/lion_apost.scap",
    "alt_init_clusters/student7_shampoo_bottle_view1_presentation_apost.scap",
    "alt_init_clusters/04sketch_apost.scap",
    "alt_init_clusters/08sketch_apost.scap",
    "alt_init_clusters/09sketch_apost.scap",
  ],
  //"alt5": [
    //"data/BowTie01_tutorial.scap",
    //"alt_init_clusters/12345_apost.scap",
    //"alt_init_clusters/building_apost.scap",
    //"alt_init_clusters/BowTie01_apost.scap",
    //"alt_init_clusters/carc_apost.scap",
    //"alt_init_clusters/duck_apost.scap",
    //"alt_init_clusters/Bunny02Fxd_apost.scap",
    //"alt_init_clusters/Koala04_apost.scap",
    //"alt_init_clusters/Penguinfxd01_apost.scap",
    //"alt_init_clusters/ring_apost.scap",
  //],
  //"alt6": [
    //"data/BowTie01_tutorial.scap",
    //"alt_init_clusters/fish_apost.scap",
    //"alt_init_clusters/Flower03_apost.scap",
    //"alt_init_clusters/Giraffe02_apost.scap",
    //"alt_init_clusters/grandpa_apost.scap",
    //"alt_init_clusters/house_apost.scap",
    //"alt_init_clusters/building_apost.scap",
    //"alt_init_clusters/SharkArtistC02fxd01_apost.scap",
    //"alt_init_clusters/TriceratopsArtistC02fxd02_apost.scap",
    //"alt_init_clusters/Tucanfxd01_apost.scap",
  //],
  //"alt7": [
    //"data/BowTie01_tutorial.scap",
    //"alt_init_clusters/archi10c_apost.scap",
    //"alt_init_clusters/BB04_apost.scap",
    //"alt_init_clusters/lady_apost.scap",
    //"alt_init_clusters/Bunny08fxd01c_apost.scap",
    //"alt_init_clusters/fairydenc_apost.scap",
    //"alt_init_clusters/geometry_apost.scap",
    //"alt_init_clusters/girl_apost.scap",
    //"alt_init_clusters/GOEagle03_apost.scap",
  //],
  //"alt8": [
    //"data/BowTie01_tutorial.scap",
    //"alt_init_clusters/GOSmart06_apost.scap",
    //"alt_init_clusters/LbkEagle02_apost.scap",
    //"alt_init_clusters/LbkSmart03_apost.scap",
    //"alt_init_clusters/mecha4c_apost.scap",
    //"alt_init_clusters/mouse7c_apost.scap",
    //"alt_init_clusters/Pig01c_apost.scap",
    //"alt_init_clusters/Pig02fxd01_apost.scap",
    //"alt_init_clusters/veyron11c_apost.scap",
  //]
};
const ungroupedSequences = {
  test_ungrouped: true,
};
